services:
  - type: web
    name: smart-farming-api
    env: python
    buildCommand: "pip install --upgrade pip && pip install --only-binary=:all: -r requirements.txt"
    startCommand: "gunicorn app:app"
    region: oregon
    plan: free
